/* eslint-disable */
// Auto-generated types

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UnitsSchemaJson {
  /**
   * This interface was referenced by `UnitsSchemaJson`'s JSON-Schema definition
   * via the `patternProperty` "^[a-z_]+$".
   */
  [k: string]: {
    name: string;
    aliases: string[];
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RecipeSchemaJson {
  id: string;
  title: string;
  tags?: string[];
  image?: string;
  first_made?: string;
  last_made?: string;
  subrecipes?: string[];
  ingredients: {
    ref: string;
    qty: number;
    unit: string;
    note?: string;
  }[];
  instructions: {
    step: number;
    text: string;
    image?: string;
  }[];
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IngredientsSchemaJson {
  /**
   * This interface was referenced by `IngredientsSchemaJson`'s JSON-Schema definition
   * via the `patternProperty` "^[a-z_]+$".
   */
  [k: string]: {
    name: string;
    default_unit: string;
    recommendations?: {
      name: string;
      link: string;
    }[];
  };
}

